---
- name: create ext volume
  file: state=directory path={{ ext_kibana_volume }}
  tags:
    - docker
    - kibana

- name: put kibana config
  template: src=kibana.yml dest={{ ext_kibana_volume }}/kibana.yml
  register: kibana_config
  tags:
    - docker
    - kibana

- name: start a kibana container
  docker:
    image: gitinsky/kibana:latest
    state: "{{ 'restarted' if kibana_config.changed else 'reloaded' }}"
    hostname: "kibana-{{ ansible_hostname }}"
    ports:
        - "8080:5601"
        - "9300:9300"
    volumes:
      - "{{ ext_kibana_volume }}/kibana.yml:/kibana/config/kibana.yml"
    name: kibana
    restart_policy: always
    command: /kibana/bin/kibana
  tags:
    - docker
    - kibana
