---
- name: create ext volume
  file: state=directory path={{ ext_kibana_volume }}
  tags:
    - docker
    - kibana

- name: put kibana config
  template: src=config.js dest={{ ext_kibana_volume }}/config.js
  register: kibana_config
  tags:
    - docker
    - kibana

- name: start a kibana container
  docker:
    image: gitinsky/kibana:0.1.0
    state: "{{ 'restarted' if kibana_config.changed else 'reloaded' }}"
    hostname: "kibana-{{ ansible_hostname }}"
    ports:
        - "8080:80"
        - "9300:9300"
    volumes:
      - "{{ ext_kibana_volume }}/config.js:/kibana/src/config.js"
    name: kibana
    restart_policy: always
    command: /usr/sbin/nginx -g "daemon off;"
  tags:
    - docker
    - kibana
